-- CreateTable
CREATE TABLE `Convicts` (
    `ID_ZASUDZ` INTEGER NOT NULL AUTO_INCREMENT,
    `FIO_ZASUDZ` VARCHAR(191) NOT NULL,
    `DATE_NARODZH` DATETIME(3) NULL,
    `ADRESS_ZASUDZ` VARCHAR(191) NOT NULL,
    `CONTACT_ZASUDZ` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_ZASUDZ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Investigators` (
    `ID_SLIDCHY` INTEGER NOT NULL AUTO_INCREMENT,
    `FIO_SLIDCHY` VARCHAR(191) NOT NULL,
    `POSADA_SLIDCHY` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_SLIDCHY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CrimeArticles` (
    `ID_STATYA` INTEGER NOT NULL AUTO_INCREMENT,
    `NUMBER_STATYA` VARCHAR(191) NOT NULL,
    `DESCRIPTION_STATYA` TEXT NOT NULL,

    PRIMARY KEY (`ID_STATYA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Cases` (
    `ID_SPRAVY` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_ZASUDZ` INTEGER NOT NULL,
    `ID_SLIDCHY` INTEGER NOT NULL,
    `STATUS_SPRAVY` ENUM('активна', 'закрита', 'очікує розгляду') NOT NULL,

    PRIMARY KEY (`ID_SPRAVY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CaseLinks` (
    `ID_SPRAVY` INTEGER NOT NULL,
    `ID_STATYA` INTEGER NOT NULL,
    `DATE_SPRAVY` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID_SPRAVY`, `ID_STATYA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Sentences` (
    `ID_SENTENCE` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_ZASUDZ` INTEGER NOT NULL,
    `ID_SPRAVY` INTEGER NOT NULL,
    `START_DATE` DATETIME(3) NOT NULL,
    `END_DATE` DATETIME(3) NULL,
    `TERM_YEARS` INTEGER NULL,
    `TYPE_POKARANNYA` ENUM('позбавлення волі', 'виправні роботи', 'умовне', 'штраф') NOT NULL,
    `LOCATION_POKARANNYA` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_SENTENCE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Users` (
    `ID_USER` INTEGER NOT NULL AUTO_INCREMENT,
    `LOGIN` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `ROLE` ENUM('admin', 'slidchiy') NOT NULL DEFAULT 'slidchiy',
    `ID_SLIDCHY` INTEGER NULL,

    UNIQUE INDEX `Users_LOGIN_key`(`LOGIN`),
    UNIQUE INDEX `Users_ID_SLIDCHY_key`(`ID_SLIDCHY`),
    PRIMARY KEY (`ID_USER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Cases` ADD CONSTRAINT `Cases_ID_ZASUDZ_fkey` FOREIGN KEY (`ID_ZASUDZ`) REFERENCES `Convicts`(`ID_ZASUDZ`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Cases` ADD CONSTRAINT `Cases_ID_SLIDCHY_fkey` FOREIGN KEY (`ID_SLIDCHY`) REFERENCES `Investigators`(`ID_SLIDCHY`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CaseLinks` ADD CONSTRAINT `CaseLinks_ID_SPRAVY_fkey` FOREIGN KEY (`ID_SPRAVY`) REFERENCES `Cases`(`ID_SPRAVY`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CaseLinks` ADD CONSTRAINT `CaseLinks_ID_STATYA_fkey` FOREIGN KEY (`ID_STATYA`) REFERENCES `CrimeArticles`(`ID_STATYA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Sentences` ADD CONSTRAINT `Sentences_ID_ZASUDZ_fkey` FOREIGN KEY (`ID_ZASUDZ`) REFERENCES `Convicts`(`ID_ZASUDZ`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Sentences` ADD CONSTRAINT `Sentences_ID_SPRAVY_fkey` FOREIGN KEY (`ID_SPRAVY`) REFERENCES `Cases`(`ID_SPRAVY`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Users` ADD CONSTRAINT `Users_ID_SLIDCHY_fkey` FOREIGN KEY (`ID_SLIDCHY`) REFERENCES `Investigators`(`ID_SLIDCHY`) ON DELETE SET NULL ON UPDATE CASCADE;
