-- CreateTable
CREATE TABLE `Convict` (
    `ID_ZASUDZ` INTEGER NOT NULL AUTO_INCREMENT,
    `FIO_ZASUDZ` VARCHAR(191) NOT NULL,
    `DATE_NARODZH` DATETIME(3) NULL,
    `ADRESS_ZASUDZ` VARCHAR(191) NOT NULL,
    `CONTACT_ZASUDZ` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_ZASUDZ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Investigator` (
    `ID_SLIDCHY` INTEGER NOT NULL AUTO_INCREMENT,
    `FIO_SLIDCHY` VARCHAR(191) NOT NULL,
    `POSADA_SLIDCHY` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_SLIDCHY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CrimeArticle` (
    `ID_STATYA` INTEGER NOT NULL AUTO_INCREMENT,
    `NUMBER_STATYA` VARCHAR(191) NOT NULL,
    `DESCRIPTION_STATYA` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_STATYA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Case` (
    `ID_SPRAVY` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_ZASUDZ` INTEGER NULL,
    `ID_SLIDCHY` INTEGER NULL,
    `STATUS_SPRAVY` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_SPRAVY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CaseLink` (
    `ID_SPRAVY` INTEGER NOT NULL,
    `ID_STATYA` INTEGER NOT NULL,
    `DATE_SPRAVY` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID_SPRAVY`, `ID_STATYA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Case` ADD CONSTRAINT `Case_ID_ZASUDZ_fkey` FOREIGN KEY (`ID_ZASUDZ`) REFERENCES `Convict`(`ID_ZASUDZ`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Case` ADD CONSTRAINT `Case_ID_SLIDCHY_fkey` FOREIGN KEY (`ID_SLIDCHY`) REFERENCES `Investigator`(`ID_SLIDCHY`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CaseLink` ADD CONSTRAINT `CaseLink_ID_SPRAVY_fkey` FOREIGN KEY (`ID_SPRAVY`) REFERENCES `Case`(`ID_SPRAVY`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CaseLink` ADD CONSTRAINT `CaseLink_ID_STATYA_fkey` FOREIGN KEY (`ID_STATYA`) REFERENCES `CrimeArticle`(`ID_STATYA`) ON DELETE RESTRICT ON UPDATE CASCADE;
